# Generated by Django 6.0.6 on 2026-06-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrihubapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriber_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
