# Generated by Django 6.0.6 on 2026-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrihubapp', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('government', 'Government Schemes'), ('market', 'Market Prices'), ('technology', 'Agricultural Technology'), ('weather', 'Weather Updates'), ('crop', 'Crop Management'), ('livestock', 'Livestock'), ('export', 'Export & Import'), ('research', 'Research & Innovation'), ('general', 'General Agriculture')], default='general', max_length=50)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
