# Generated by Django 6.0.6 on 2026-06-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrihubapp', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('government', 'Government Schemes'), ('market', 'Market Prices'), ('technology', 'Agricultural Technology'), ('weather', 'Weather Updates'), ('crop', 'Crop Management'), ('livestock', 'Livestock'), ('export', 'Export & Import'), ('research', 'Research & Innovation'), ('general', 'General Agriculture'), ('Business', 'Agriculture Business')], default='general', max_length=50),
        ),
    ]
