# Generated by Django 6.0.6 on 2026-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrihubapp', '0005_alter_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture'), ('technology', 'Technology'), ('education', 'Education'), ('market', 'Market'), ('research', 'Research'), ('general', 'General'), ('webinar', 'Webinar'), ('success_story', 'Success Story'), ('innovation', 'Innovation'), ('business', 'Business'), ('other', 'Other')], default='general', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
