# Generated by Django 5.2.5 on 2026-07-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrihubapp', '0006_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.PositiveIntegerField(default=0)),
                ('students', models.PositiveIntegerField(default=0)),
                ('partners', models.PositiveIntegerField(default=0)),
                ('linkedin_followers', models.PositiveIntegerField(default=0)),
                ('instagram_followers', models.PositiveIntegerField(default=0)),
                ('youtube_followers', models.PositiveIntegerField(default=0)),
                ('whatsapp_followers', models.PositiveIntegerField(default=0)),
                ('webinars', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
