# Generated by Django 5.2.5 on 2026-07-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrihubapp', '0007_sitestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IN', 'Internship'), ('CT', 'Contract')], default='FT', max_length=50)),
                ('is_urgent', models.BooleanField(default=False)),
                ('eligibility_notes', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('apply_instructions', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
