# Generated by Django 5.2.5 on 2026-07-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrihubapp', '0008_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
